version: "3.8"
services:
  devops-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev # Point to the development Dockerfile
    volumes:
      - .:/app # Mount the project directory inside the container for live reloading
    restart: always