global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter_devops'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor_devops'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter_altlokalt'
    static_configs:
      - targets: ['16.16.28.87:9100']

  - job_name: 'cadvisor_altlokalt'
    static_configs:
      - targets: ['16.16.28.87:8080']
