---
- name: Remove useless packages from the cache
  become: true
  apt:
    autoclean: yes

- name: Create a 1GB swap file
  become: true
  command:  fallocate -l 1G /swapfile

- name: Secure swap file by setting up correct permissions
  become: true
  command:  chmod 600 /swapfile

- name: Set up the swap area
  become: true
  command:  mkswap /swapfile

- name: Enable swap
  become: true
  command: swapon /swapfile

- name: Make this swap setting persist by adding following line in /etc/fstab
  become: true
  command: echo '/swapfile swap swap defaults 0 0' | tee -a /etc/fstab